# Generated by Django 5.0.2 on 2024-02-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_airline_flights_runways'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airline', to='core.airline'),
        ),
        migrations.AlterField(
            model_name='runways',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='core.airport'),
        ),
    ]
