# Generated by Django 5.0.2 on 2024-02-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_flights_airline_alter_runways_airport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flights',
            new_name='Flight',
        ),
        migrations.RenameModel(
            old_name='Runways',
            new_name='Runway',
        ),
    ]
